### ISSUE TITLE
AttributeError: 'MLX90614'

### ISSUE THREAD

**Issue by geir75** [Conr86/PyMLX90614#3]
**Describe the bug**
After installing: pip3 install PyMLX90614 at raspberry pi and running the code:

from smbus2 import SMBus
from mlx90614 import MLX90614

bus = SMBus(1)
sensor = MLX90614(bus, address=0x5A)
print sensor.get_amb_temp()
print sensor.get_obj_temp()
bus.close()

I receive only:
AttributeError: 'MLX90614' object has no attribute 'get_amb_temp'. 
I'm running Raspbian GNU/Linux 11 (bullseye).

**Comment by WilliamsJack** [comment]
I believe the Python Package Index has an older version of this repository. You might want to try `sensor.get_ambient()` and `sensor.get_object_1()` instead of `sensor.get_amb_temp()` and `sensor.get_obj_temp()` respectively.

Alternatively, you can install the latest version with `python -m pip install git+https://github.com/sightsdev/PyMLX90614.git@c700518023c62af66e0abe4a2ee0bfda94ef45d9`

I'll see if we can update the project on the Python Package Index soon. :-)

**Comment by geir75** [comment]
It worked given your answer. Thanks WilliamsJack!

**Comment by Conr86** [comment]
Latest version should now be on PyPI. Thanks for reporting this @geir75
